// clang-format off
#include "native_bridge_support/vdso/interceptable_functions.h"

DEFINE_INTERCEPTABLE_STUB_FUNCTION(JNI_OnLoad);
DEFINE_INTERCEPTABLE_STUB_FUNCTION(_ZN7android17GraphicBufferImpl11UnmapStaticEl);
DEFINE_INTERCEPTABLE_STUB_FUNCTION(_ZN7android17GraphicBufferImpl15GetStrideStaticEl);
DEFINE_INTERCEPTABLE_STUB_FUNCTION(_ZN7android17GraphicBufferImpl21GetNativeBufferStaticEl);
DEFINE_INTERCEPTABLE_STUB_FUNCTION(_ZN7android17GraphicBufferImpl3MapE9AwMapModePPv);
DEFINE_INTERCEPTABLE_STUB_FUNCTION(_ZN7android17GraphicBufferImpl5UnmapEv);
DEFINE_INTERCEPTABLE_STUB_FUNCTION(_ZN7android17GraphicBufferImpl6CreateEii);
DEFINE_INTERCEPTABLE_STUB_FUNCTION(_ZN7android17GraphicBufferImpl7ReleaseEl);
DEFINE_INTERCEPTABLE_STUB_FUNCTION(_ZN7android17GraphicBufferImpl9MapStaticEl9AwMapModePPv);
DEFINE_INTERCEPTABLE_STUB_FUNCTION(_ZN7android17GraphicBufferImplC2Ejj);
DEFINE_INTERCEPTABLE_STUB_FUNCTION(_ZN7android17GraphicBufferImplD2Ev);
DEFINE_INTERCEPTABLE_STUB_FUNCTION(_ZN7android19RegisterDrawFunctorEP7_JNIEnv);
DEFINE_INTERCEPTABLE_STUB_FUNCTION(_ZN7android20RaiseFileNumberLimitEv);
DEFINE_INTERCEPTABLE_STUB_FUNCTION(_ZN7android21RegisterDrawGLFunctorEP7_JNIEnv);
DEFINE_INTERCEPTABLE_STUB_FUNCTION(_ZN7android21RegisterGraphicsUtilsEP7_JNIEnv);
DEFINE_INTERCEPTABLE_STUB_FUNCTION(_ZNK7android17GraphicBufferImpl15GetNativeBufferEv);
DEFINE_INTERCEPTABLE_STUB_FUNCTION(_ZNK7android17GraphicBufferImpl9GetStrideEv);
DEFINE_INTERCEPTABLE_STUB_FUNCTION(_ZNK7android17GraphicBufferImpl9InitCheckEv);

static void __attribute__((constructor(0))) init_stub_library() {
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", JNI_OnLoad);
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", _ZN7android17GraphicBufferImpl11UnmapStaticEl);
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", _ZN7android17GraphicBufferImpl15GetStrideStaticEl);
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", _ZN7android17GraphicBufferImpl21GetNativeBufferStaticEl);
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", _ZN7android17GraphicBufferImpl3MapE9AwMapModePPv);
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", _ZN7android17GraphicBufferImpl5UnmapEv);
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", _ZN7android17GraphicBufferImpl6CreateEii);
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", _ZN7android17GraphicBufferImpl7ReleaseEl);
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", _ZN7android17GraphicBufferImpl9MapStaticEl9AwMapModePPv);
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", _ZN7android17GraphicBufferImplC2Ejj);
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", _ZN7android17GraphicBufferImplD2Ev);
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", _ZN7android19RegisterDrawFunctorEP7_JNIEnv);
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", _ZN7android20RaiseFileNumberLimitEv);
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", _ZN7android21RegisterDrawGLFunctorEP7_JNIEnv);
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", _ZN7android21RegisterGraphicsUtilsEP7_JNIEnv);
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", _ZNK7android17GraphicBufferImpl15GetNativeBufferEv);
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", _ZNK7android17GraphicBufferImpl9GetStrideEv);
  INIT_INTERCEPTABLE_STUB_FUNCTION("libwebviewchromium_plat_support.so", _ZNK7android17GraphicBufferImpl9InitCheckEv);
}
// clang-format on
